# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with Unittest
      env:
        export SECRET_KEY="django-insecure-d4tga9e*rr&q(-zwryp_i42hhjf18rj17e_8x!99xg-!kr8b=o"
        export EMAIL_FROM_USER=mobidoc726@gmail.com
        export EMAIL_HOST_PASSWORD='qywxyurfwjjjwyum'
        export DB_NAME=errandslistdb
        export DB_ENGINE=django.db.backends.postgresql
        export DB_PASSWORD=testg
        export DB_HOST=localhost
        export DB_PORT=5432  
      run: |
        python manage.py test
